Repository puppetlabs/puppetlabs-sqlserver, pull requests merged in 2023-03, with the labels that each got.

#416 (Maint) - Add nightly and PR testing
  .fixtures.yml
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  lib/puppet/provider/sqlserver.rb
  lib/puppet/provider/sqlserver_features/mssql.rb
  lib/puppet/provider/sqlserver_instance/mssql.rb
  lib/puppet_x/sqlserver/features.rb
  lib/puppet_x/sqlserver/sql_connection.rb
  spec/acceptance/sqlserver_config_spec.rb
  spec/acceptance/sqlserver_database_spec.rb
  spec/acceptance/sqlserver_instance_spec.rb
  spec/acceptance/sqlserver_login_spec.rb
  spec/acceptance/sqlserver_role_spec.rb
  spec/acceptance/sqlserver_user_spec.rb
  spec/acceptance/z_last_sqlserver_features_spec.rb
  spec/spec_helper_acceptance_local.rb
  spec/sql_testing_helpers.rb
  spec/unit/puppet/provider/sqlserver_instance_spec.rb
  spec/unit/puppet/sqlserver_spec_helper.rb
  spec/unit/puppet_x/sql_connection_spec.rb
Labels: maintenance, needs-squash

#420 (CONT-490) - Add support for SQL Server 2022
  README.md
  lib/puppet/provider/sqlserver_features/mssql.rb
  lib/puppet/provider/sqlserver_instance/mssql.rb
  lib/puppet_x/sqlserver/features.rb
  lib/puppet_x/sqlserver/server_helper.rb
  metadata.json
  spec/acceptance/z_last_sqlserver_features_spec.rb
  spec/spec_helper_acceptance_local.rb
  spec/sql_testing_helpers.rb
  spec/unit/puppet_x/sql_connection_spec.rb
Labels: feature

#424 pdksync - (CONT-768) Pin puppetlabs-puppet_agent
  .fixtures.yml
Labels: maintenance
